# Generated by Django 2.0.13 on 2019-02-13 05:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=200)),
                ('titulo', models.CharField(max_length=300)),
                ('foto', models.CharField(max_length=20)),
                ('texto', models.TextField()),
                ('tags', models.CharField(max_length=200)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('prioridade', models.IntegerField(default=3)),
            ],
        ),
    ]
