# Generated by Django 2.0.13 on 2019-02-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_noticia_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='categoria',
            field=models.CharField(default='Geral', max_length=30),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='autor',
            field=models.CharField(default='Zé Geraldo', max_length=200),
        ),
    ]
