# Generated by Django 2.0.13 on 2019-02-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_noticia_subtitulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='foto',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
