# Generated by Django 2.0.13 on 2019-02-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190215_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='fotoNoticia',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
